server:
  port:
    9091
spring:
    application:
      name: DOMINOS
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      url: jdbc:mysql://localhost:3306/dominos-service
      password: root
    jpa:
      hibernate:
       ddl-auto: update

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
      fetch-registry: 'true'
      register-with-eureka: 'true'
    instance:
      hostname: localhost